version: '3'
services:
  node-app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    command: npm start  
